version: '3'

services:
  web:
    build: .
    ports:
      - ${PORT}:8000
    command:  >
      sh -c "python manage.py runserver 0.0.0.0:8000"

    volumes:
      - .:/code
      - ./static:/static
      - ./media:/media
    depends_on:
      - db
  
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - ${DB_PORT}:3306
    volumes:
      - mysql-data:/var/lib/mysql
  
volumes:
  mysql-data: